import type { Metadata } from "next";
import { getUserMovieListPublicId } from "@/features/list/actions/getUserMovieListPublicId";
import { isAuthenticated } from "@/features/auth/services/session";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Menu from "@/components/Menu";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const isVerified = await isAuthenticated();
	const listPublicId = isVerified
		? await getUserMovieListPublicId(isVerified.userId)
		: null;

	return (
		<html lang="ja">
			<body className={`antialiased`}>
				<Header />

				<main className="min-h-[calc(100dvh-var(--header-height))] pb-20">{children}</main>

				<Menu listPublicId={listPublicId} />

				<Footer />
			</body>
		</html>
	);
}
