import type { Metadata } from "next";
import { currentUserPublicListId } from "@/features/shared/actions/currentUserPublicListId";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Menu from "@/components/Menu";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const result = await currentUserPublicListId();
	const publicListId = result.success ? result.data.publicListId : null;

	return (
		<html lang="ja">
			<body className={`antialiased`}>
				<Header isLoggedIn={result.success} />

				<main className="min-h-[calc(100dvh-var(--header-height))] pb-20">
					{children}
				</main>

				<Menu publicListId={publicListId} isLoggedIn={result.success} />

				<Footer />
			</body>
		</html>
	);
}
