import { Suspense } from "react";
import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Menu from "@/components/Menu";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={`antialiased`}>
				<Header />

				<main className="min-h-[calc(100dvh-var(--header-height))] pb-20">
					{children}
				</main>

				<Footer />

				<Suspense fallback={null}>
					<Menu />
				</Suspense>
			</body>
			
		</html>
	);
}
