name: Test

on:
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: 依存関係インストール
        run: npm ci

      - name: テスト
        run: npm run test -- --reporter=default --reporter=junit --outputFile=test-results/junit.xml

      - name: テスト結果をPRに掲載
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: Vitest
          path: test-results/junit.xml
          reporter: java-junit
